profiles:

  gpt:

    default_behaviour: |
      /record
      /clean
    base_url: http://server:8000
    seed: 1
    temperature: 0
    session: gpt4
    model: gpt-4-0125-preview
    system_prompt: |
      You are a friendly AI assistant 

  default:

    default_behaviour: |
      /record
      /clean
    base_url: http://server:8000
    seed: 1
    temperature: 0
    session: default
    record: true
    model: ollama/mistral-openorca
    system_prompt: |
      You are a friendly AI assistant 

  coder:

    default_behaviour: |
      /record
      /clean
    base_url: http://server:8000
    seed: 1
    temperature: 0
    session: coder
    record: true
    model: ollama/wizardcoder:13b-python
    system_prompt: |
      You are a friendly AI assistant that assist with development in linux enviroment.
      Be concice and clear, only answer the question the user asked.
      When solving a problem think through the steps one by one and then output the final solution.